site_name: JAVA成神之路
nav:
- 主页: index.md
- 基础篇:
    - 基础知识: 基础篇/基础知识.md
    - 面向对象: 基础篇/面向对象.md
    - 异常处理: 基础篇/异常处理.md
    - 开发工具: 基础篇/开发工具.md
- 进阶篇: 
    - 多线程: 进阶篇/多线程.md
    - JAVA常用类: 进阶篇/JAVA常用类.md
    - JAVA集合: 进阶篇/JAVA集合.md
    - IO: 进阶篇/IO.md
    - 枚举类和注解: 进阶篇/枚举类和注解.md
- 进阶篇(框架):
    - Spring: 进阶篇(框架)/Spring.md
    - SpringBoot: 进阶篇(框架)/SpringBoot.md
- 进阶篇(新特性):
    - Java8的其它新特性: 进阶篇(新特性)/Java8的其它新特性.md
- 高级篇:
    - 数据结构与算法: 高级篇/数据结构与算法.md
    - 剑指offer: 高级篇/剑指offer.md
    - 编译原理: 高级篇/编译原理.md
    - 操作系统: 高级篇/操作系统.md
- 架构篇:
    - 分布式: 架构篇/分布式.md
- 扩展篇:
    - 机器学习: 扩展篇/机器学习.md
    - 深度学习: 扩展篇/深度学习.md
    - 强化学习: 扩展篇/强化学习.md
    - 云计算: 扩展篇/云计算.md

- 关于作者: about authors.md
theme: readthedocs
