site_name: JAVA成神之路
nav:
- 主页: index.md
- 基础篇:
    - JAVA基础: Basic/基础.md
    - 面向对象: Basic/面向对象.md
    - 异常处理: Basic/异常处理.md
    - IO: Basic/IO.md
    - 多线程: Basic/多线程.md
- 进阶篇: 
    - 框架: Advanced/Spring开发.md
- 关于作者: about authors.md
theme: readthedocs