site_name: JAVA成神之路
nav:
- 主页: index.md
- 基础篇:
    - JAVA基础: 基础篇/基础.md
    - 面向对象: 基础篇/面向对象.md
    - 异常处理: 基础篇/异常处理.md
    - IO: 基础篇/IO.md
    - 多线程: 基础篇/多线程.md
- 进阶篇:
- 高级篇:
    - Java并发编程:
    - Spring开发: 高级篇/Spring开发.md
    - 数据结构与算法:
    - 编译原理:
    - 数据库:
    - 操作系统:
- 架构篇:
- 扩展篇:
- 关于作者: about authors.md
theme: readthedocs